[project]
name = "kielmat"
version = "0.0.5"
description = "The KielMotionAnalysisToolbox (KielMAT) is a Python-based toolbox for processing motion data."
license = "MIT"
readme = "README.md"
requires-python = ">=3.10,<3.13"
authors = [
    { name = "Masoud Abedinifar", email = "Masoud.Abedinifar@uksh.de" },
    { name = "Julius Welzel", email = "j.welzel@neurologie.uni-kiel.de" },
    { name = "Walter Maetzler", email = "w.maetzler@neurologie.uni-kiel.de" },
    { name = "Clint Hansen", email = "c.hansen@neurologie.uni-kiel.de" },
    { name = "Robbin Romijnders", email = "r.romijnders@neurologie.uni-kiel.de" },
]
maintainers = [
    { name = "Masoud Abedinifar", email = "Masoud.Abedinifar@uksh.de" },
    { name = "Julius Welzel", email = "j.welzel@neurologie.uni-kiel.de" },
    { name = "Robbin Romijnders", email = "r.romijnders@neurologie.uni-kiel.de" },
]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "pandas>=2",
    "scipy>=1.11.0",
    "numpy>=1.25",
    "pywavelets>=1.4.1,<2.0.0",
    "ipykernel>=6.26.0,<7.0.0",
    "matplotlib>=3.8.1,<4.0.0",
    "tpcp>=0.27.0,<0.28.0",
    "qmt>=0.2.4,<0.3.0",
    "vqf>=2.0.0,<3.0.0",
    "h5py>=3.10.0,<4.0.0",
    "polars>=0.20.5,<0.21.0",
    "seaborn>=0.13.1,<0.14.0",
    "json-repair>=0.8.0,<0.9.0",
    "pyarrow>=15.0.0,<16.0.0",
    "bids-validator>=1.14.4,<2.0.0",
    "actipy>=3.0.5,<4.0.0",
    "pooch>=1.8.2,<2.0.0",
    "openneuro-py>=2024.2.0,<2025.0.0",
    "pre-commit>=4.0.1,<5.0.0",
]

[project.urls]
homepage = "https://neurogeriatricskiel.github.io/KielMAT/"
repository = "https://github.com/neurogeriatricskiel/KielMAT"
documentation = "https://neurogeriatricskiel.github.io/KielMAT"

[project.optional-dependencies]
docs = [
    "mkdocs",
    "mkdocs-material",
    "mkdocs-material-extensions",
    "pymdown-extensions",
    "mkdocstrings",
    "mkdocstrings-python",
    "mkdocs-jupyter",
    "mkdocs-autorefs",
]

[dependency-groups]
dev = [
    "pytest-cov>=4.1.0,<5.0.0",
    "pytest>=7.4.3,<8.0.0",
    "black>=24.4.2,<25.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["kielmat"]

[tool.hatch.build.targets.sdist]
include = ["kielmat", "CHANGELOG.md", "README.md"]
